spring.application.name=javaCrudApp

# Configuración de la base de datos PosgreSQL:
spring.profiles.include=secret

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
